language: node_js
node_js:
  - "12.11"

sudo: true

branches:
  only:
    - master

before_script:
  - npm i -g @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: ./dist/
  on:
    branch: gh-pages